version: "3.3"

services:
  odoo13:
    image: odoo:17.0
    container_name: odoo17
    command: -- --dev=reload
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons:rw
    environment: 
      - HOST=postgres_db
    networks:
      - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.odoo.rule=Host(`crm.interimubackend.nl`)"
        - traefik.http.services.odoo.loadbalancer.server.port=8069
        - "traefik.http.routers.odoo.entrypoints=websecure"
        - "traefik.http.routers.odoo.tls=true"
        - "traefik.http.routers.odoo.tls.certresolver=myresolver"

  adminer:
    image: adminer
    restart: always
    networks:
      - traefik
    ports:
      - 8080:8080
      
  postgres_db:
    image: postgres:12.0
    container_name: postgres_db
    restart: always
    networks:
      - traefik
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  traefik:
    external: true
